name: night_fall_restaurant_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.4.1

  # sqflite
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  #lottie file
  lottie: ^2.6.0

  # networking dependencies
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.0

  # bloc
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

  # for dependency injection
  get_it: ^7.6.4

  # shared prefs:
  shared_preferences: ^2.2.2

  # number formatter
  intl: ^0.18.1
  number_text_input_formatter: ^1.0.0+7

  # image picker
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/anim/animation_lnom89oi.json
    - assets/anim/success_anim.json
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/images/coca_cola.jpeg
    - assets/images/double_arrow_up_thin.png
  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: Ktwod
      fonts:
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-Light.ttf
          weight: 200
        - asset: assets/fonts/K2D-Regular.ttf
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 500
